config/routes.rb
DeviseOnAjax::Application.routes.draw do
  devise_for :users, :controllers => {:confirmations => 'confirmations'}

  resources :users, :only => [] do
    put :favorite_word
  end

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :favorite_word
  # attr_accessible :title, :body

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    if password != password_confirmation
      self.errors[:password_confirmation] << "does not match password"
    end
    password == password_confirmation && !password.blank?
  end

  protected

  def password_required?
    super if confirmed?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  def show
    self.resource = resource_class.find_by_confirmation_token(params[:confirmation_token])
    super if resource.confirmed?
  end

  def confirm
    self.resource =
      resource_class.find_by_confirmation_token(params[resource_name][:confirmation_token])
    if (resource.update_attributes(params[resource_name].except(:confirmation_token)) &&
        resource.password_match?)
      self.resource =
        resource_class.confirm_by_token(params[resource_name][:confirmation_token])
      set_flash_message :notice, :confirmed
      sign_in_and_redirect(resource_name, resource)
    else
      render :action => "show"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  respond_to :js

  def favorite_word
    @user = User.find params[:user_id]
    if @user.update_attributes(params[:user])
      respond_with @user
    else
      render :text => 'Oops!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_favorite_color_form.html.erb
<div id="favorite_word">
  <h3> Tell us your favorite word
  <%= form_for current_user, :url => user_favorite_word_path(current_user), remote: true, :html => {:class => 'favorite_word_form'} do |f| %>
    <%= f.text_field :favorite_word %>
    <%= f.submit 'Submit' %>
  <% end %>
</div>

app/views/home/_sign_in_form.html.erb
<div id="sign_in">
  <h3>Sign in</h3>
  <%= form_for resource, :as => resource_name, :url => user_session_path do |f| %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
    <%= f.submit 'Sign in' %>
    <%= link_to "Forgot your password?", new_password_path('user') %>
  <% end %>
</div>

app/views/home/_sign_up_form.html.erb
<div id="sign_up">
  <h3>Sign up</h3>
  <%= form_for resource, :as => resource_name, :url => registration_path(resource_name), :remote => true, :html => {:class => 'signup-form'} do |f| %>
    <%= f.text_field :email, :required => true, :placeholder => 'your email here!' %>
    <%= f.submit 'Sign up' %>
  <% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h2>Welcome <%= current_user.email %></h2>
  <% if current_user.confirmed? %>
    <p><%= link_to 'Edit profile', edit_user_registration_path %></p>
  <% else %>
    <% if current_user.favorite_word == nil %>
      <%= render 'favorite_color_form' %>
    <% else %>
      <p> Your favorite word is <%= current_user.favorite_word %>.
    <% end %>
  <% end %>
  <p><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></p>
<% else %>
  <div class="new_signup_container">
    <div class="form_container">
      <%= render 'sign_in_form' %>
      <%= render 'sign_up_form' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseOnAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_favorite_word.html.erb
<p> Your favorite word is <%= @user.favorite_word %>.</p>

app/views/users/favorite_word.js.erb
$('#favorite_word').remove();
$('.new_signup_container').append("<%=j render 'favorite_word' %>");